[cr137] Removes unused TS import.
 TypeScript compilation failed. Used tsconfig gen/third_party/devtools-frontend/src/front_end/panels/network/network-tsconfig.json

 third_party/devtools-frontend/src/front_end/panels/network/RequestAdblockView.ts(6,1): error TS6133: 'i18n' is declared but its value is never read.