[cr151][plaster] Adds missing dependency.
12:11:26  In file included from ../../chrome/browser/ui/webui/help/test_version_updater.cc:5:
12:11:26  In file included from ../../chrome/browser/ui/webui/help/test_version_updater.h:9:
12:11:26  ../../brave/chromium_src/chrome/browser/ui/webui/help/version_updater.h(9,10): fatal error: 'brave/browser/sparkle_buildflags.h' file not found
12:11:26      9 | #include "brave/browser/sparkle_buildflags.h"
12:11:26        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:11:26  1 error generated.