Try removing unsigned
CI failed due to signed vs unsigned comparison.

```
23:09:39  ../..\third_party/googletest/src/googletest/include/gtest/gtest.h(1352,11):
error: comparison of integers of different signs: 'const unsigned int' and 'const int' [-Werror,-Wsign-compare]
23:09:39   1352 |   if (lhs == rhs) {
23:09:39        |       ~~~ ^  ~~~
23:09:39  ../..\third_party/googletest/src/googletest/include/gtest/gtest.h(1371,12):
note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<unsigned int, int>' requested here
23:09:39   1371 |     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
23:09:39        |            ^
23:09:39  ../../brave/browser/ui/tabs/test/split_view_browser_data_unittest.cc(118,3):
note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<unsigned int, int, nullptr>' requested here
23:09:39    118 |   EXPECT_EQ(0u, std::distance(data().tiles_.cbegin(),
```