Changed `android:multiArch` to `"false"` since our bundle has single ABI
Starting from Android 15 a verification during install had been added. If the verification fails, it gives
	Error: INSTALL_FAILED_INTERNAL_ERROR: Error deriving application ABI: The multiArch app's native libs don't support all the natively supported ABIs of the device.
Verification works for packages with targetSDK >= 35, so it wasn't triggered on cr127.

Related Android commit:
https://android.googlesource.com/platform/frameworks/base/+/a55ab0340e16baa56e79c22688c349cc327a3361

	[PM] Force multi-arch app native libs match natively ABIs

	Force the match when the below conditions are satisfied
	1. When the feature flag is On.
	2. It is an multi-arch APP `android:multiarch = true` in its manifest
	3. The targetSdkVersion of the apk >= VANILLA_ICE_CREAM
	4. The installation is not the cpuAbiOverride case.

	The match rule:
	1.If the system supports 32 bit abi, but there is no native library
	matching natively 32 bit abis
	2. If the system supports 64 bit abi, but there is no native library
	matching natively 64 bit abis

	Test: atest CtsSliceTestCases
	Test: atest CtsAppTestStubsApp2
	Test: atest CtsWidgetTestCases
	Test: atest CtsInputMethodTestCases
	Test: atest CtsOsHostTestCases
	Test: atest CtsPackageManagerHostTestCases
	Test: atest CtsDisplayTestCases
	Test: atest CtsPackageManagerTestCases
	Test: atest CtsAppEnumerationTestCases
	Bug: 282783453
	Change-Id: I8bbda14786be6bb7ad8d4fae80c7426ec7af71b2

Target SDK changed at Chromium commit:
https://source.chromium.org/chromium/chromium/src/+/75c9571291eba719e4d66ee0516a7b1f328dfba8

          Android V: rolling DEPS entries to start using Android V by default

          Bug: [341901237](https://issuetracker.google.com/341901237)
          Change-Id: [Iec05a0a95a4892dd7dbe4b18e3f0c158f679c79c](https://chromium-review.googlesource.com/q/Iec05a0a95a4892dd7dbe4b18e3f0c158f679c79c)
          Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5649225