Fixed crash at Content Filtering (#25812)
fixes https://github.com/brave/brave-browser/issues/41402

Crash happened at app menu => Settings => Brave Shields & privacy => Content Filtering.

Tombstone
```
java.lang.ClassCastException: org.chromium.chrome.browser.settings.SettingsActivity cannot be cast to org.chromium.chrome.browser.settings.BraveSettingsActivity
at org.chromium.chrome.browser.shields.ContentFilteringFragment.onAttach(ContentFilteringFragment.java:86)
```

Upstream had added a new place to create Intent for Settings activity.

Related Chromium change:
https://source.chromium.org/chromium/chromium/src/+/d4af6a2c4ccc6427aa7df0f2beacf61793459e66

	[Settings] Introduce a central place to construct intents

	SettingsIntentUtil becomes the central place to construct intents
	launching the settings activity.

	Bug: b/356743945
	Change-Id: Id6988af4a182fe6603bb02c9dae8b2ac48f80fed
	Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5832868