[cr145] Keep glic GRDs in resource ID filtering to avoid missing includes
Otherwise there is a build error:
Traceback (most recent call last):
  File "/mnt/wd2t/projects/brave-browser-3/src/out/android_Release_arm64/../../tools/grit/grit.py", line 17, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/wd2t/projects/brave-browser-3/src/tools/grit/grit/grit_runner.py", line 313, in Main
    return toolobject.Run(options, args[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/wd2t/projects/brave-browser-3/src/tools/grit/grit/tool/build.py", line 265, in Run
    self.res = grd_reader.Parse(opts.input,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/wd2t/projects/brave-browser-3/src/tools/grit/grit/grd_reader.py", line 252, in Parse
    handler.root.AssignFirstIds(filename_or_stream, defines)
  File "/mnt/wd2t/projects/brave-browser-3/src/tools/grit/grit/node/misc.py", line 657, in AssignFirstIds
    raise Exception('Please update %s and add a first id for %s (%s).' %
Exception: Please update ../../out/android_Release_arm64/gen/tools/gritsettings/default_resource_ids and add a first id for chrome/browser/glic/resources/browser_resources.grd (includes).