Fix case-sensitivity error in Windows builds
This happened when the drive letter was lower- instead of upper-case:

Traceback (most recent call last):
  File "C:\src\tools\grit\grit.py", line 17, in <module>
    sys.exit(grit.grit_runner.Main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\tools\grit\grit\grit_runner.py", line 307, in Main
    toolobject = _GetToolInfo(tool)[_FACTORY]()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\tools\grit\grit\grit_runner.py", line 25, in ToolFactoryBuild
    import grit.tool.build
  File "C:\src\tools\grit\grit\tool\build.py", line 21, in <module>
    from grit import grd_reader
  File "C:\src\tools\grit\grit\grd_reader.py", line 17, in <module>
    from grit.node import mapping
  File "C:\src\tools\grit\grit\node\mapping.py", line 12, in <module>
    from grit.node import empty
  File "C:\src\tools\grit\grit\node\empty.py", line 10, in <module>
    from grit.node import include
  File "C:\src\tools\grit\grit\node\include.py", line 12, in <module>
    import grit.format.html_inline
  File "C:\src\tools\grit\grit\format\html_inline.py", line 22, in <module>
    from grit.format import minifier
  File "C:\src\tools\grit\grit\format\minifier.py", line 35, in <module>
    from brave_chromium_utils import inline_chromium_src_override; inline_chromium_src_override(globals(), locals())
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\brave\script\brave_chromium_utils.py", line 111, in inline_chromium_src_override
    chromium_src_override = get_chromium_src_override(orig_file)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\brave\script\brave_chromium_utils.py", line 64, in get_chromium_src_override
    assert path.startswith(src_dir), (path, src_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ('C:\\src\\tools\\grit\\grit\\format\\minifier.py', 'c:\\src')