Fixing `brave_wayback_machine` dependency order
This change adds `brave_wayback_machine` buildflags as a public dep for
`//brave/browser/ui`, in order to make sure the build flags are built
before `//chrome/browser/ui`. This is to avoid build failures due to
transient inclusions like in:

In file included from ../../chrome/browser/safe_browsing/chrome_password_protection_service.cc:102:
In file included from ../../brave/chromium_src/chrome/browser/ui/views/frame/browser_view.h:9:
../../brave/browser/ui/brave_browser_window.h:12:10: fatal error: 'brave/components/brave_wayback_machine/buildflags/buildflags.h' file not found
   12 | #include "brave/components/brave_wayback_machine/buildflags/buildflags.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Chromiu change