Added missing dep.
Fixes

20:02:09  In file included from ../../brave/browser/notifications/ads_notification_handler.cc:10:
20:02:09  In file included from ../../brave/browser/brave_ads/ads_service_factory.h:12:
20:02:09  ../../brave/components/brave_ads/browser/ads_service.h:17:10: fatal error: 'brave/vendor/bat-native-ads/include/bat/ads/public/interfaces/ads.mojom.h' file not found
20:02:09  #include "brave/vendor/bat-native-ads/include/bat/ads/public/interfaces/ads.mojom.h"
20:02:09           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:02:09  1 error generated.