[cr134] [Android] Fixed BravePrivacySettingsTest.testParentItems
	java.lang.AssertionError: expected:<31> but was:<30>
	Reason - "clear_browsing_data_advanced" section was removed from Chromium prefs

Related Chromium change:
https://source.chromium.org/chromium/chromium/src/+/a49153686134a72ff189024392df6aad09e71fb0

	[Quick Delete] Clean up kQuickDeleteAndroidFollowup flag

	Clean up Quick Delete phase 2 feature checks now that the experiment is
	fully launched. This includes removing the obsolete tabbed layout and
	basic tab from CBD on Android.

	OBSOLETE_HISTOGRAM[History.ClearBrowsingData.UserDeletedFromTab]=No longer logged

	Bug: 40255099
	Change-Id: I340afa9692f17ad3b472f501522a9e6ff8fb061c
	Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6162502