NotificationHelperWin::CanShowNativeNotifications cannot be const
It calls IsNotificationEnabled which is not const (and cannot be const
because it calls InitializeToastNotifier which modifies member var).

Rolling back the change to const introduced in
https://github.com/brave/brave-core/pull/14207

Windows error:

../../brave/browser/brave_ads/notification_helper/notification_helper_win.cc(164,16): error: 'this' argument to member function 'InitializeToastNotifier' has type 'const brave_ads::NotificationHelperWin', but function is not marked const
  HRESULT hr = InitializeToastNotifier();
               ^~~~~~~~~~~~~~~~~~~~~~~
../..\brave/browser/brave_ads/notification_helper/notification_helper_win.h(37,11): note: 'InitializeToastNotifier' declared here
  HRESULT InitializeToastNotifier();
          ^
1 error generated.