Fixed build failure (#34465)
Build failed at asan build.
Need to relay brave/components/sidebar/browser target to propagate its public deps upward.

05:23:53  stderr:
05:23:53  In file included from ../../brave/browser/ui/views/frame/layout/brave_browser_view_tabbed_layout_impl.cc:16:
05:23:53  In file included from ../../brave/browser/ui/views/sidebar/sidebar_container_view.h:14:
05:23:53  In file included from ../../brave/browser/ui/sidebar/sidebar.h:9:
05:23:53  In file included from ../../brave/components/sidebar/browser/sidebar_service.h:17:
05:23:53 
 ../../brave/components/sidebar/browser/sidebar_item.h:10:10: fatal error: 'brave/components/brave_talk/buildflags/buildflags.h' file not found
05:23:53     10 | #include "brave/components/brave_talk/buildflags/buildflags.h"
05:23:53        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
05:23:53  1 error generated.