Use vpython with download_rust_deps on Windows.
The following Chromium change is causing an issue with Python3 on Win:

https://chromium.googlesource.com/chromium/src/+/efdcb8407e0d9139e142aaf236cffb97b5e6d7f1%5E%21/#F0

It added the wheel for psutil 5.7.2 to .vpython3. But there doesn't appear to
be a prebuilt wheel for the particular architecture (amd64_cp38_cp38m). Even
when I try to use pip to install that version of psutil, pip downloads the
source distribution and tries to build locally (which fails since we don't
have python-dev installed) instead of grabbing a prebuilt package.

With vpython3 get the following error:

________ running 'vpython3 script/download_rust_deps.py' in 'C:\bb4\brave-browser\src/brave'
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] original error: no such package: infra/python/wheels/psutil/windows-amd64_cp38_cp38m
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241]
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] goroutine 73:
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #0 go.chromium.org/luci/cipd/client/cipd/client.go:1838 - cipd.(*clientImpl).humanErr()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #1 go.chromium.org/luci/cipd/client/cipd/client.go:816 - cipd.(*clientImpl).ResolveVersion()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #2 go.chromium.org/luci/cipd/client/cipd/resolver.go:176 - cipd.(*Resolver).resolveVersion.func1()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #3 go.chromium.org/luci/common/sync/promise/promise.go:84 - promise.(*Promise).runGen()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #4 runtime/asm_amd64.s:1374 - runtime.goexit()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241]
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] goroutine 72:
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] From frame 0 to 0, the following wrappers were found:
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241]   internal reason: MultiError 1/1: following first non-nil error.
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241]
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #0 go.chromium.org/luci/cipd/client/cipd/ensure/file.go:255 - ensure.(*File).Resolve.func1.1()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241]   reason: failed to resolve infra/python/wheels/psutil/windows-amd64_cp38_cp38m@version:5.7.2 (line 0)
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241]
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #1 go.chromium.org/luci/common/sync/parallel/runner.go:51 - parallel.(*WorkItem).execute()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #2 go.chromium.org/luci/common/sync/parallel/runner.go:149 - parallel.(*Runner).dispatchLoopBody.func2()
[E2021-02-09T20:44:06.398243-05:00 32528 0 annotate.go:241] #3 runtime/asm_amd64.s:1374 - runtime.goexit()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241]
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] goroutine 1:
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #0 go.chromium.org/luci/vpython/venv/config.go:183 - venv.(*Config).makeEnv()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241]   reason: failed to resolve packages
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241]
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #1 go.chromium.org/luci/vpython/venv/venv.go:163 - venv.With()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #2 go.chromium.org/luci/vpython/run.go:62 - vpython.Run() [E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #3 go.chromium.org/luci/vpython/application/application.go:320 - application.(*application).mainImpl()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #4 go.chromium.org/luci/vpython/application/application.go:408 - application.(*Config).Main.func1()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #5 go.chromium.org/luci/vpython/application/support.go:46 - application.run()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #6 go.chromium.org/luci/vpython/application/application.go:407 - application.(*Config).Main()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #7 vpython/main.go:109 - main.mainImpl()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #8 vpython/main.go:115 - main.main()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #9 runtime/proc.go:204 - runtime.main()
[E2021-02-09T20:44:06.399254-05:00 32528 0 annotate.go:241] #10 runtime/asm_amd64.s:1374 - runtime.goexit()
Error: Command 'vpython3 script/download_rust_deps.py' returned non-zero exit status 1 in C:\bb4\brave-browser\src/brave

-----

Also, see https://bugs.chromium.org/p/chromium/issues/detail?id=1141986