[Win] Fixes build errors due to name collision with MSFT.
The errors below happen because one of our overrides ends up
including windows.h (winuser.h) which `#define LoadAccelerators
LoadAcceleratorsW(...)`. This causes the class method in the original .h
file to be renamed. The original .cc file, on the other hand explicitly
`#undef LoadAccelerators` after including <windows.h> and so we end up
with mismatching method name in the .h and .cc files.

Traced it down to:
chrome/browser/ui/views/frame/browser_view.h
-> #include "chrome/browser/ui/views/intent_picker_bubble_view.h"
   -> #include "chrome/browser/ui/views/location_bar/location_bar_bubble_delegate_view.h"
      -> #include "ui/views/bubble/bubble_dialog_delegate_view.h"
         -> #include "ui/views/bubble/bubble_border.h"
	    -> chromium_src override
               -> #include <Windows.h>

Inlcusion on Windows.h in that header doesn't appear to be needed.

Also, modified other haders that included Windows.h by instead,
including `base/win/windows_types.h` which has basic Windows
types defined. Moved including Windows.h to the corresponding .cc
files.

The errors:
---------------------
In file included from ..\..\brave\chromium_src\chrome\browser\ui\views\frame\browser_view.cc:14:
..\..\brave\chromium_src\chrome\browser\ui\views\frame/../../../../../../../chrome/browser/ui/views/frame/browser_view.cc(3079,3): error: use of undeclared identifier 'LoadAccelerators'; did you mean 'LoadAcceleratorsW'?
  LoadAccelerators();
  ^~~~~~~~~~~~~~~~
  LoadAcceleratorsW
..\..\brave\chromium_src\chrome\browser\ui\views\frame/../../../../../../../chrome/browser/ui/views/frame/browser_view.h(772,8): note: 'LoadAcceleratorsW' declared here
  void LoadAccelerators();
       ^
../../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/um\winuser.h(7131,27): note: expanded from macro 'LoadAccelerators'
                          ^
In file included from ..\..\brave\chromium_src\chrome\browser\ui\views\frame\browser_view.cc:14:
..\..\brave\chromium_src\chrome\browser\ui\views\frame/../../../../../../../chrome/browser/ui/views/frame/browser_view.cc(3541,19): error: out-of-line definition of 'LoadAccelerators' does not match any declaration in 'BrowserView'; did you mean 'LoadAcceleratorsW'?
void BrowserView::LoadAccelerators() {
                  ^~~~~~~~~~~~~~~~
                  LoadAcceleratorsW
..\..\brave\chromium_src\chrome\browser\ui\views\frame/../../../../../../../chrome/browser/ui/views/frame/browser_view.h(772,8): note: 'LoadAcceleratorsW' declared here
  void LoadAccelerators();
       ^
../../../../../Program Files (x86)/Windows Kits/10/include/10.0.19041.0/um\winuser.h(7131,27): note: expanded from macro 'LoadAccelerators'
                          ^
2 errors generated.
---------------------

Chromium change:

https://chromium.googlesource.com/chromium/src/+/f6278aeb0156fcf581d90c0a7ee537fb80d8bf6b

commit f6278aeb0156fcf581d90c0a7ee537fb80d8bf6b
Author: Bruce Dawson <brucedawson@chromium.org>
Date:   Tue Aug 24 21:25:34 2021 +0000

    Avoiding windows.h using CHROME_MSG, etc.

    In order to avoid having platform_events.h including windows.h just to
    get the definition of the MSG struct (thus polluting ~1,000 translation
    units with the windows.h macros) this change defines the CHROME_MSG
    struct (following the pattern of CHROME_SRWLOCK and others) and uses it.
    In the few (two) places where the MSG type is required in order to call
    in to Windows a reinterpret_cast function does the conversion.

    This change also removes some includes of windows.h and objidl.h from
    headers, and adds includes of windows.h to .cc files that need it. The
    net result is a significant drop in how many translation units get
    namespace polluted by windows.h.

    This change touches many files, but most of the changes are just
    replacing MSG with CHROME_MSG.

    This change has been tested to ensure that it builds with
    is_chrome_branded=true and enable_nacl=true to reduce the risk of
    compile breakage on other bots.

    Bug: 796644