[Android] Fixes ChromeTabbedActivity.java build error.
Got the following error:

../../chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java:1131: error: incompatible types: Object cannot be converted to Profile
                             TrackerFactory.getTrackerForProfile(profile).notifyEvent(
                                                                 ^
Patched the file to use explicit parameter type in the lambda.
Not sure why this is not a problem for Chromium build. Will add
a follow-up issue to investigate.

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/d0158f92090943278abbcf1c13355c9d9233d5c3

commit d0158f92090943278abbcf1c13355c9d9233d5c3
Author: David Trainor <dtrainor@chromium.org>
Date:   Fri Aug 7 19:55:21 2020 +0000

    git squash commit for branch_4147.

    b78ae4b1fbe0f868b53b1102c9ac59907bd7b7d5
    [Android] CallbackController for canceling Callbacks and Runnables

    This patch adds CallbackController that can wrap Callbacks
    and Runnables in order to protect them from being invoked after
    an object they refer to has been destroyed. This late invocation
    can come for example from a UI which has received a callback
    to signal UI events, like changing focus.

    Detailed documentation in JavaDoc.

    Change-Id: I012f647c4b93ca378a1987da593d77a5890dafef
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2267409
    Reviewed-by: Sky Malice <skym@chromium.org>
    Reviewed-by: David Trainor <dtrainor@chromium.org>
    Reviewed-by: Tommy Nyquist <nyquist@chromium.org>
    Commit-Queue: Filip Gorski <fgorski@chromium.org>
    Cr-Commit-Position: refs/heads/master@{#787884}
    (cherry picked from commit 5a00bc836598f4882f170ac60a994642858cf85a)

    20cf4888fbcdb1a59955c37fbb2e81fe1511ba4b
    Add support for reengagement notification

    This patch adds the functionality required for an IPH system to trigger
    one of three re-engagement notifications.  The IPH changes are -

    - Starting ChromeTabbedActivity will be flagged as engagement.
    - Starting a CCT will check criteria and decide whether or not to notify
    the user about Chrome.

    The feature is integrated into Chrome through the two main
    RootUiCoordinators and is guarded by an overall feature flag (disabling
    all added code) in addition to the IPH feature configurations.

    This CL also adds a OneShotCallback, which makes it easier to get a
    single value back from an ObservableSupplier.

    Bug: 1108002
    Change-Id: Ia23827337b325550ff16259d97d81bf223de3566
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2311827
    Commit-Queue: David Trainor <dtrainor@chromium.org>
    Reviewed-by: Ted Choc <tedchoc@chromium.org>
    Reviewed-by: Alexei Svitkine <asvitkine@chromium.org>
    Reviewed-by: Tommy Nyquist <nyquist@chromium.org>
    Cr-Commit-Position: refs/heads/master@{#794174}
    (cherry picked from commit 3701317183f5893caa86a0382c3ddb6fefd0e961)

    98050af680ece4e98f200a15b63cd7cc496f2afd
    Add the reengagement notification to chrome://flags.

    Make it possible to easily test the reengagement notification.

    Bug: 1108002
    Change-Id: I1fd85e9338164e55bea18b9e0208806aad47a996
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2335637
    Commit-Queue: David Trainor <dtrainor@chromium.org>
    Reviewed-by: Tommy Nyquist <nyquist@chromium.org>
    Cr-Commit-Position: refs/heads/master@{#794319}
    (cherry picked from commit 724ade07784fdf7a681e49b173d91d2e6ff6239f)

    805358f1de50b7c534b275c4f71b07bfa83ff317
    Move all reengagement notification code behind flags

    - Duplicate DefaultBrowserInfo to hide the refactored version.
    - Make ChromeTabbedActivity check the enabled state before hitting the
    tracker.
    - Expose the feature flag in chrome://flags.

    (cherry picked from commit a38e60e172acb9068aaf6419f8009185ef6410d0)

    Bug: 1108002