[iOS] Workaround an upstream bug with credential provider extension.
We build with `ios_enable_credential_provider_extension = false` but
the recent upstream change causes errors in this configuration:

Initially:
ERROR Unresolved dependencies.
//ios/chrome/app:credential_provider_migrator_app_agent(//build/toolchain/ios:ios_clang_x64)
  needs //ios/chrome/browser/credential_provider:credential_provider(//build/toolchain/ios:ios_clang_x64)

And, also:
../../ios/chrome/app/main_controller.mm:663:29: error: use of undeclared identifier 'CredentialProviderAppAgent'
  [self.appState addAgent:[[CredentialProviderAppAgent alloc] init]];
                            ^
1 error generated.

Filed an upstream bug with this info:
https://bugs.chromium.org/p/chromium/issues/detail?id=1245295

Chromium change that caused the issue:

https://chromium.googlesource.com/chromium/src.git/+/b32f389ea82506054ab7fda2ce6abbabe0c2a797

commit b32f389ea82506054ab7fda2ce6abbabe0c2a797
Author: Javier Ernesto Flores Robles <javierrobles@chromium.org>
Date:   Tue Aug 10 18:41:12 2021 +0000

    [iOS][Credential-Provider] Import CPE passwords to password manager

    Move Credential Provider Extension (CPE) passwords from temporal
    storage to password manager.

    CPE stores the password in the Keychain already, so there is no need
    to re-encrypt passwords.

    Bug: 1224983

Chromium upstream fixes applied as patches (not available in cr94 yet):

https://chromium.googlesource.com/chromium/src.git/+/ab3809244ea889dd3232708c700893e230a559ea

commit ab3809244ea889dd3232708c700893e230a559ea
Author: Sylvain Defresne <sdefresne@chromium.org>
Date:   Mon Aug 23 15:03:06 2021 +0000

    [ios] Fix build when credential provider is disabled

    Change //ios/chrome/app:credential_provider_migrator_app_agent target
    to only be build when ios_enable_credential_provider_extension (as it
    depends on //ios/chrome/browser/credential_providers that isn't build
    if ios_enable_credential_provider_extension is false).

    Bug: none

https://chromium.googlesource.com/chromium/src.git/+/712ab90025a19b49b18f1d3d40ed2143d6149ca5

commit 712ab90025a19b49b18f1d3d40ed2143d6149ca5
Author: Javier Ernesto Flores Robles <javierrobles@chromium.org>
Date:   Wed Sep 8 18:48:59 2021 +0000

    [iOS][Credential-Provider] Guard CredentialProviderAppAgent

    Bug: 1245295