Patched in a missing dependency.
Build error on CI for Android:

20:26:04  In file included from ../../chrome/browser/updates/announcement_notification/announcement_notification_service.cc:17:
20:26:04  ../../brave/chromium_src/chrome/grit/generated_resources.h:9:10: fatal error: 'brave/grit/brave_generated_resources.h' file not found
20:26:04  #include "brave/grit/brave_generated_resources.h"
20:26:04           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:26:04  1 error generated.

Looks like a Chromium bug. Chromium change is:

https://chromium.googlesource.com/chromium/src/+/77c4d4c42f406fe1541fdd145b8201ab78ff9651

commit 77c4d4c42f406fe1541fdd145b8201ab78ff9651
Author: Xing Liu <xingliu@chromium.org>
Date:   Tue Jan 28 03:58:56 2020 +0000

    Announcement notification: Fix navigation to URL.

    Currently when clicking on the "Review" button, on Mac, it will always
    not navigate to the expected URL. On Debian, sometimes nothing happens.

    On Mac, if the notification has no origin, then click event will not be
    forwarded to NotificationHandler. This CL removes the origin check.

    Also changed the URL navigation API used to open the URL.

    Bug: 1042124

Specifically in chrome/browser/updates/announcement_notification/announcement_notification_service.cc:

@@ -14,8 +14,10 @@
 #include "chrome/browser/profiles/profile_attributes_storage.h"
 #include "chrome/browser/profiles/profile_manager.h"
 #include "chrome/browser/updates/announcement_notification/announcement_notification_metrics.h"
+#include "chrome/grit/generated_resources.h"

but the BUILD.gn file was not updated with the dependency on generated
resources.