[Android][Build] Fixed missing deps for BraveMessageQueueMediator
Error message was

12:41:59  build step: __brave_android_junit_brave_junit_tests_org.chromium.chrome.browser.messages__header___build_toolchain_android_android_clang_x64__rule "./obj/brave/android/junit/brave_junit_tests_org.chromium.chrome.browser.messages.turbine.jar"
12:41:59  siso_rule: android/turbine
12:41:59  stderr:
12:41:59  ../../brave/android/junit/src/org/chromium/chrome/browser/messages/BraveMessageQueueMediatorTest.java:51: error: could not resolve BraveMessageQueueMediator
12:41:59      private BraveMessageQueueMediator mMediator;
12:41:59              ^
12:41:59  💡 One or more errors due to missing GN deps 💡
12:41:59  Hint: To show missing deps: "autoninja -config no-remote-javac ..." or: /mnt/engflow/worker/work/0/exec/out/x/siso_failed_commands.sh
12:41:59
12:41:59
12:41:59  [4491/4513] 17.54s - ACTION //brave/test:brave_junit_tests__compile_resources(//build/toolchain/android:android_clang_x64)
12:41:59  build failed

Fixed https://github.com/brave/brave-browser/issues/56870