Also use Boost's multiprecision types for 128-bit (un)signed integers
We in principle only migrated to using Boost's types for 256-bit
integers, which worked well for Linux, but on Android and Windows
that is causing the following build error:

```
  In file included from ../../brave/components/brave_wallet/common/eth_sign_typed_data_helper.cc:15:
  In file included from ../..\brave/components/brave_wallet/common/brave_wallet_types.h:12:
  In file included from ../../brave/third_party/boost/multiprecision/include\boost/multiprecision/cpp_int.hpp:17:
  ../../brave/third_party/boost/multiprecision/include\boost/multiprecision/number.hpp(64,17): error: no viable overloaded '='
        m_backend = canonical_value(v);
        ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
  ../../brave/third_party/boost/multiprecision/include\boost/multiprecision/detail/number_compare.hpp(81,76): note: in instantiation of function template specialization 'boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, boost::multiprecision::et_off>::number<unsigned _BitInt(128)>' requested here
     typename boost::multiprecision::detail::number_from_backend<T, U>::type t(b);
                                                                             ^
  ../../brave/third_party/boost/multiprecision/include\boost/multiprecision/detail/number_compare.hpp(94,11): note: in instantiation of function template specialization 'boost::multiprecision::default_ops::eval_gt_imp<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, unsigned _BitInt(128)>' requested here
     return eval_gt_imp(a, b, tag_type());
```

...due to eventually having to compare Boost's 256-bit integers with
Clang's 128-bit integers, so let's switch to using Boost's types for
both sizes to prevent the problem.

Additionally, let's also do the same adjustment we did for 256-bit
signed integers to limit the max and min value of int128_t to use
127 bits only for the magnitude (vs 128) and 1 bit for the sign.