[cr136] Prevent using hardcoded json value for print settings
Enum value of printing::mojom or printing constants can be changed from
time to time.
This causes Windows only print preview test failure because printer type
now became PrinterType::kLocal which trigers
failed PrinterQuery::UpdatePrintableArea() in
PrintViewManagerBase::UpdatePrintSettings().

Chromium change:
https://chromium.googlesource.com/chromium/src/+/14d938d28bcc9edbff1d8f703d9a5ac70fecb09

commit 14d938d28bcc9edbff1d8f703d9a5ac70fecb09a
Author: Lei Zhang <thestig@chromium.org>
Date:   Mon Mar 24 16:02:18 2025 -0700

    Remove unused enum values from enum printing.mojom.PrinterType

    Now that this enum is no longer marked as Stable, delete the unused
    values. Then do the same on the TypeScript side, and delete all
    references. Along the way, modernize RecordGetPrintersTimeHistogram() to
    use std::string_view.

    Change-Id: Ifa4684821b3177cc6cc0d45d33968b95d477d1a2