Patches .vpython3 with an upstream fix.
Fixes brave/brave-browser#17205

npm run sync error similar to:

INFO: pip is looking at multiple versions of atomicwrites to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /tmp/vpython_bootstrap201185403/requirements.txt (line 33) and py==1.5.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested py==1.5.3
    pytest 6.2.2 depends on py>=1.8.2

This is a fix for https://bugs.chromium.org/p/chromium/issues/detail?id=1231439

https://chromium.googlesource.com/chromium/src/+/a2b0fa8ea08111655f2f8465530220d892b9cf08

commit a2b0fa8ea08111655f2f8465530220d892b9cf08
Author: Brian Ryner <bryner@google.com>
Date:   Thu Jul 22 18:54:22 2021 +0000

    Update the "py" wheel to a version that is compatible with pytest-6.2.2.

    Bug: 1231439