Adds missing dep.
 ../../brave/browser/ui/brave_rewards/rewards_panel_coordinator.h:11:10: fatal error: 'brave/components/brave_rewards/common/mojom/rewards_panel.mojom.h' file not found
    11 | #include "brave/components/brave_rewards/common/mojom/rewards_panel.mojom.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.