Upgrade from Chromium 128 to Chromium 129 (uplift to 1.70.x). (#25514)
* Merge pull request #25126 from jagadeshjai/fix__clean_debug_build_linker_error

Fix Debug build Linker issue

* Merge pull request #24966 from brave/cr129

Upgrade from Chromium 128 to Chromium 129.

* Post cr129 merge build fixes for 1.70.x branch.

* Fixes Linux release build. (#25526)

Fixes official Linux release build.

The build fails with:

09:30:10  > gn gen /home/ubuntu/workspace/brave-browser-build-linux-x64-nightly/src/out/Release --check
09:30:10
 ERROR at //build/config/compiler/compiler.gni:324:3: Assertion failed.
09:30:10    assert(
09:30:10    ^-----
09:30:10  Can't do non-component builds at symbol_level=2 without use_debug_fission=true
09:30:10  See //build/config/compiler/compiler.gni:325:7:
09:30:10        symbol_level != 2 || current_toolchain != default_toolchain ||
09:30:10        ^-------------------------------------------------------------
09:30:10  This is where it was set.
09:30:10  See //BUILD.gn:13:1: whence it was imported.
09:30:10  import("//build/config/compiler/compiler.gni")

Due to Chromium change:

https://source.chromium.org/chromium/chromium/src/+/81024e91fddf6e045dcd9a8a04186c8cdbcbb4c0

commit 81024e91fddf6e045dcd9a8a04186c8cdbcbb4c0
Author: Nico Weber <thakis@chromium.org>
Date:   Thu Aug 1 02:54:08 2024 +0000

    Reland^2 "linux/build: Enable fission for (symbol_level = 2) release builds as well"

    This is a reland of commit b7da3afa43ecb6a1a4839c4f91e798a6d72b221f

    The CL got reverted for breaking android-official, and a comment
    on the original review mentioned that it also broke a few cros bots
    like arm-generic-cq.

    For the reland, this now also allows non-fission static symbol_level 2
    for android and chromeos.

    Original change's description:
    > Reland "linux/build: Enable fission for (symbol_level = 2) release builds as well"
    >
    > This is a reland of commit c031e3aa3a7a0ad71715655e140ba52ffa82a08d
    > The reland removes an assert on macOS (where is_debug_fission isn't
    > used -- darwin toolchains have always used something like fission,
    > but under a different name).
    >
    > Original change's description:
    > > linux/build: Enable fission for (symbol_level = 2) release builds as well
    > >
    > > Looks like full-symbol non-component builds are getting too big for
    > > debug info even in release builds.
    > >
    > > Turn on fission by default on linux in release builds as well.
    > >
    > > This might affect official builds, where dump_syms etc might not
    > > handle fission yet. If this is a problem, we'll have to fix this
    > > at some point, but short-term we can not do this for official
    > > builds in that case. (zequanwu@ says CrOS enabled fission already,
    > > encountered dump_syms issues, and those already got fixed.
    > > And a linux-official try run is green. We'll see!)
    > >
    > > (Component builds don't need fission yet, but for simplicity I'm
    > > enabling fission independent of is_component_build.)
    > >
    > > Bug: 353915727

* Adds missing dep.

 ../../brave/browser/ui/brave_rewards/rewards_panel_coordinator.h:11:10: fatal error: 'brave/components/brave_rewards/common/mojom/rewards_panel.mojom.h' file not found
    11 | #include "brave/components/brave_rewards/common/mojom/rewards_panel.mojom.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.

* Merge pull request #25528 from brave/129.0.6668.42_master

Upgrade from Chromium 129.0.6668.31 to Chromium 129.0.6668.42.

* [Icons]: Fix settings icon updates from CR129 (#25522)

* [Android] Fix for settings launcher (#25549)

Chromium change:
https://source.chromium.org/chromium/chromium/src/+/e86c3572f7012a64517e54c098984c0d44afe1f6

[Android] Use SettingsLauncherFactory directly from settings Fragments

Also add SettingsLauncherFactory#setInstanceForTesting().

Clean up passing around of the SettingsLauncher to Fragments.

Low-Coverage-Reason: LARGE_SCALE_REFACTOR
Bug: 354019554

---------

Co-authored-by: Brian Clifton <brian@clifton.me>
Co-authored-by: Jay Harris <jay.harris@outlook.co.nz>
Co-authored-by: samartnik <30602739+samartnik@users.noreply.github.com>