Fix TS5055 typescript errors in /ui/webui/resources.
The errors are:

error TS5055: Cannot write file 'out/Debug/gen/brave/ui/webui/resources/tsc/br_elements/br_shared_style.css.d.ts' because it would overwrite input file.

error TS5055: Cannot write file 'out/Debug/gen/brave/ui/webui/resources/tsc/br_elements/br_shared_vars.css.d.ts' because it would overwrite input file.

error TS5055: Cannot write file 'out/Debug/gen/brave/ui/webui/resources/tsc/br_elements/br_toolbar/br_toolbar.d.ts' because it would overwrite input file.

error TS5055: Cannot write file 'out/Debug/gen/brave/ui/webui/resources/tsc/br_elements/br_toolbar/br_toolbar_search_field.d.ts' because it would overwrite input file.

I think these happen because tsc is trying to resolve imports via our
brave_path_mappings defined in brave/tools/typescript/sources.gni that
end up pointing to the output directory:

      "chrome://resources/brave/*": [
        "./tsc/*"
      ],
      "//resources/brave/*": [
        "./tsc/*"
      ]

To prevent lookup, updated the imports of the files from the same
target to use relative paths.

Chromium change:

https://chromium.googlesource.com/chromium/src/+/1df55739b54d5d630caa38cbe97f041b84f19428

commit 1df55739b54d5d630caa38cbe97f041b84f19428
Author: rbpotter <rbpotter@chromium.org>
Date:   Wed Feb 28 00:49:55 2024 +0000

    WebUI: Detect hidden .d.ts file dependencies in ts_library()

    In some cases, developers use ts_library() path_mappings to map URL
    prefixes to src/ directories containing TypeScript definitions files.
    However, any files imported using these mappings are not actually added
    to |inputs| for gn, unless they are also listed in the ts_library()
    project's |definitions| argument. This leads to compile failures in
    remote execution environments, and to gn not correctly re-building
    targets when .d.ts files they depend on are modified.

    This CL uses TS compiler's listFilesOnly option to output all files
    encountered when building a target, and then checks that any .d.ts files
    in the list that are not in a generated directory are correctly listed
    in |definitions|. It throws an error asking the developer to add such
    files to |definitions| if any missing .d.ts files are found.

    Started by dpapad@ at:
    https://chromium-review.googlesource.com/c/chromium/src/+/5321764

    Bug: 326005022