Fix rollup optimization failures due to new 'tsc' extension
Adapt the expected dirname in |preprocessed_folder| to allow JavaScript
files generated out of TypeScript files that include our Brave-specific
modules to find them when doing the rollup optimization, at build time.

This prevents this build error from happening on optimized builds:

[!] Error: Could not resolve './brave_overrides/index.js' from gen/chrome/browser/resources/extensions/tsc/extensions.js
Error: Could not resolve './brave_overrides/index.js' from gen/chrome/browser/resources/extensions/tsc/extensions.js
    at error (/home/mario/work/brave-rebases/brave-browser-next/src/third_party/node/node_modules/rollup/dist/rollup.js:10162:30)
    at ModuleLoader.handleMissingImports (/home/mario/work/brave-rebases/brave-browser-next/src/third_party/node/node_modules/rollup/dist/rollup.js:17237:17)
    at ModuleLoader.<anonymous> (/home/mario/work/brave-rebases/brave-browser-next/src/third_party/node/node_modules/rollup/dist/rollup.js:17288:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/mario/work/brave-rebases/brave-browser-next/src/third_party/node/node_modules/rollup/dist/rollup.js:40:28)

Ideally, Brave's JavaScript files should be migrated to TypeScript, but
that should be done separate from the rebase, see GH issue #16553 [1].

[1] https://github.com/brave/brave-browser/issues/16553
the time being this quick hack will keep Brave building.