[cr142] Suppress `-Wunique-object-duplication` for `sandbox_win.cc` chromium_src override
Clang now detects unique object duplication by default, which is being triggered
for this module by upstream macros. We've suppressed the warning for this
chromium_src override module, as we are only linking a single object and
changing the upstream macros didn't look feasible in a non-invasive way.

We use the same technique to locally supress this warning as is used upstream in
a few scenarios.

The errors we encountered on Windows prior to this change looked like this:

  In file included from ../../brave/chromium_src/sandbox/policy/win/sandbox_win.cc:26:
  ../..\sandbox/policy/win/sandbox_win.cc(838,5): error: 'atomic_histogram_pointer' may be duplicated when built into a shared library: it is mutable, with external linkage and no import/export annotation [-Werror,-Wunique-object-duplication]
    838 |     UMA_HISTOGRAM_SPARSE(
        |     ^
  ../..\base/metrics/histogram_macros.h(408,3): note: expanded from macro 'UMA_HISTOGRAM_SPARSE'
    408 |   STATIC_HISTOGRAM_POINTER_BLOCK(          \
        |   ^
  ../..\base/metrics/histogram_macros_internal.h(105,34): note: expanded from macro 'STATIC_HISTOGRAM_POINTER_BLOCK'
    105 |     static std::atomic_uintptr_t atomic_histogram_pointer;                    \
        |                                  ^
  In file included from ../../brave/chromium_src/sandbox/policy/win/sandbox_win.cc:26:
  ../..\sandbox/policy/win/sandbox_win.cc(843,5): error: 'atomic_histogram_pointer' may be duplicated when built into a shared library: it is mutable, with external linkage and no import/export annotation [-Werror,-Wunique-object-duplication]
    843 |     UMA_HISTOGRAM_SPARSE("Process.Sandbox.IPC.ThreadDuplicateHandleErrorCode",
        |     ^
  ../..\base/metrics/histogram_macros.h(408,3): note: expanded from macro 'UMA_HISTOGRAM_SPARSE'
    408 |   STATIC_HISTOGRAM_POINTER_BLOCK(          \
        |   ^
  ../..\base/metrics/histogram_macros_internal.h(105,34): note: expanded from macro 'STATIC_HISTOGRAM_POINTER_BLOCK'
    105 |     static std::atomic_uintptr_t atomic_histogram_pointer;                    \
        |                                  ^
  2 errors generated.