Update patches for 72.0.3626.17
Note:
chrome/browser/resources/settings/passwords_and_forms_page/passwords_section.html
Was renamed to:
chrome/browser/resources/settings/autofill_page/passwords_section.html

Note:
third_party/blink/renderer/core/frame/content_settings_client.*

commit 3f827e31f04f9c3be7d3a2fe2e964a37b3cf1314
Author: Dmitry Gozman <dgozman@chromium.org>
Date:   Sat Oct 27 02:43:41 2018 +0000

    Remove blink::ContentSettingsClient

    We can use WebContentSettingsClient directly now,
    which is a part of public/platform.

    Some users of GetContentSettingsClient now have to null-check,
    while previously they assumed the client is always present
    (that's true for non-detached frames).

    Some places needed an update, because they treated null
    ContentSettingsClient differently from the default value.
    Perhaps that's not intended, but we preserve it just in case.

error: components/domain_reliability/service.cc: No such file or directory

commit aec73c860b15a0873431e32913e7e536f929da68
Author: John Abd-El-Malek <jam@chromium.org>
Date:   Sat Nov 17 00:07:11 2018 +0000

    Instantiate Domain Reliability code in NetworkContext so it works with and without the network service.