[cr143] Single argument testing::DoAll is deprecated.
stderr:
 ../../brave/components/brave_wallet/browser/cardano/cardano_wallet_service_unittest.cc:208:17: error: 'DoAll<(lambda at ../../base/test/gmock_callback_support.h:81:10)>' is deprecated: Avoid using DoAll() for single actions [-Werror,-Wdeprecated-declarations]
   208 |       .WillOnce(DoAll(RunOnceClosure(task_environment_.QuitClosure())));
       |                 ^
 ../../third_party/googletest/src/googlemock/include/gmock/gmock-actions.h:1884:1: note: 'DoAll<(lambda at ../../base/test/gmock_callback_support.h:81:10)>' has been explicitly marked deprecated here
  1884 | GTEST_INTERNAL_DEPRECATE_AND_INLINE("Avoid using DoAll() for single actions")
       | ^
 ../../third_party/googletest/src/googletest/include/gtest/internal/gtest-port.h:2327:5: note: expanded from macro 'GTEST_INTERNAL_DEPRECATE_AND_INLINE'
  2327 |   [[deprecated(msg), clang::annotate("inline-me")]]
       |     ^
 1 error generated.

Chromium change:

https://github.com/google/googletest/commit/a05c0915074bcd1b82f232e081da9bb6c205c28d

commit a05c0915074bcd1b82f232e081da9bb6c205c28d
Author: Abseil Team <absl-team@google.com>
Date:   Sat Aug 16 20:07:31 2025 -0700

    Deprecate single-argument DoAll and Invoke.

    PiperOrigin-RevId: 795969677
    Change-Id: I56d88ec715475d91fb527a9281bc62574fb4608b