[cr137][rust] `gnrt` handlebars now in strict mode
This change updates our handlebars file to be closer to what is
currently held in the chromium tree. With the switching on of the
handlebars strict mode parser, a few changes had to be made, but in
particular, it is now very trick to not emit a `rustenv = []`, so for
the sake of simplicity, this change now emits the empty value.

Chromium changes:
https://chromium.googlesource.com/chromium/src/+/78e6ff963b3543b992003cfefc2ff853aa64f6c6

commit 78e6ff963b3543b992003cfefc2ff853aa64f6c6
Author: Lukasz Anforowicz <lukasza@chromium.org>
Date:   Mon Apr 14 13:45:29 2025 -0700

    [gnrt] Enable strict mode when expanding `handlebars` templates.

    The main change in this CL is enabling "strict mode" when expanding
    `handlebars` templates.  This CL also makes minor tweaks to make
    debugging template errors easier (adding `with_context` in a few places
    + trying to preserve the name of the `.hbs` file rather than using a
    generic `"template"` name).

    Initially, this just seemed like a good idea, but it turned out that
    there actually was a typo in `removed_Cargo.toml.hbs` (`featuress`).
    This CL edits this template to 1) preserve mostly how the placeholder
    `Cargo.toml` looks like (no `features` specified for dependencies),
    but also 2) setting `default_features = false` to solidify the approach
    of not imposing any features on dependencies of placeholders.
    An alternative approach would be to fix the typo and use proper quoting,
    but this would have resulted in errors below (because this step of
    `gnrt vendor` isn't aware of `guppy`-resolved/trimmed feature set?):

        ```
        `cargo metadata` exited with an error:
        error: failed to select a version for `cc`.
            ... required by package `link-cplusplus v1.0.10`
            ... which satisfies dependency `link-cplusplus = "^1.0.9"`
                (locked to 1.0.10) of package `cxx v1.0.156`
            ... which satisfies dependency `cxx = "^1"`
                (locked to 1.0.156) of package `chromium v0.1.0 ...`
        versions that meet the requirements `^1.0` (locked to 1.2.18) are:
            1.2.18
        the package `link-cplusplus` depends on `cc`, with features: ``
            but `cc` does not have these features.
        failed to select a version for `cc` which could resolve this
            conflict
        ```

    This CL was manually tested by removing all of
    `.../chromium_crates_io/vendor/` and rerunning `gnrt vendor` and `gnrt
    gen`.

    Bug: None
    Change-Id: Ifc49f98724572d5181454e6cb542a1ecb1f105de
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6427603
    Auto-Submit: Łukasz Anforowicz <lukasza@chromium.org>
    Reviewed-by: Liza Burakova <liza@chromium.org>
    Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1446746}