[cr152][Android] Add DataProtectionNavigationController to Android TabFeatures
Chromium change:
https://source.chromium.org/chromium/chromium/src/+/99e5bc13fb71cc04061619e8e6cfe8568ffb5b69

Error fixed:
../../chrome/browser/enterprise/util/data_protection_bridge.cc:142:30: error: no member named 'data_protection_controller' in 'tabs::TabFeatures'
  142 |       tab->GetTabFeatures()->data_protection_controller();
      |       ~~~~~~~~~~~~~~~~~~~~~  ^

commit 99e5bc13fb71cc04061619e8e6cfe8568ffb5b69
Author: Alex Chen <alxchn@google.com>
Date:   Mon Jun 29 14:56:52 2026 -0700

    Add DataProtectionNavigationController to Android TabFeatures

    Similar to crrev.com/c/5734522. Only instantiate the controller if the
    profile is actively managed. Fix build issues preventing it from
    compiling.

    Bug: b:428695892
    Change-Id: Idf61645a4f0c2afad7522757b326c88b19313038
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8012371
    Commit-Queue: Alex Chen <alxchn@google.com>
    Reviewed-by: Dominique Fauteux-Chapleau <domfc@chromium.org>
    Reviewed-by: Theresa Wellington <twellington@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1654390}