[cr139] Fix leaking UX object.
616 upstream unit tests failing with

----------
 ..\..\content\public\test\content_test_suite_base.cc(105): error: Expected equality of these values:
   instance_count
     Which is: 1
   0U
     Which is: 0

 This test is leaking UX objects (e.g., Views or Widgets). This is often caused by ownership issues with Widgets and NativeWidgets
----------

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/6a4b0b6eed554a8455842730228b14df9949b370

commit 6a4b0b6eed554a8455842730228b14df9949b370
Author: Greg Thompson <grt@chromium.org>
Date:   Thu Jun 12 02:08:46 2025 -0700

    Reland "[accessibility] Fail tests that leak platform accessibility nodes"

    This is a reland of commit 10d9d86b92ac58308482449ecd4fff775b7534dc

    Original change's description:
    > [accessibility] Fail tests that leak platform accessibility nodes
    >
    > Check for live nodes and, on Windows, leaked nodes. The checks are
    > disabled on Linux due to various tests that still contain leaks.
    >
    > AX-Relnotes: n/a.
    > Bug: 40665982