[cr133][Android] Fixes importer build error due to missing strings.
../../chrome/common/importer/firefox_importer_utils.cc:335:38: error: use of undeclared identifier 'IDS_IMPORT_FROM_ICEWEASEL'
  335 |     return l10n_util::GetStringUTF16(IDS_IMPORT_FROM_ICEWEASEL);
      |                                      ^
../../chrome/common/importer/firefox_importer_utils.cc:336:36: error: use of undeclared identifier 'IDS_IMPORT_FROM_FIREFOX'
  336 |   return l10n_util::GetStringUTF16(IDS_IMPORT_FROM_FIREFOX);
      |                                    ^
2 errors generated.

Upstream has these strings only for non-Android platforms, but we are
using the importer code on Android as well, so the string need to be
re-added for Android.