Fix PermissionStatus name collision in blink
We're encountering the following compilation errors:

In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:13:
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(52,41): error: reference to 'PermissionStatus' is ambiguous
   52 |   HashMap<mojom::blink::PermissionName, PermissionStatus>
      |                                         ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(18,21): note: candidate found by name lookup is 'blink::PermissionStatus'
   18 | using mojom::blink::PermissionStatus;
      |                     ^
../..\third_party/blink/renderer/bindings/core/v8/active_script_wrappable_creation_key.h(84,16): note: candidate found by name lookup is 'blink::PermissionStatus'
   84 |   friend class PermissionStatus;
      |                ^
In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:13:
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(52,41): error: reference to 'PermissionStatus' is ambiguous
   52 |   HashMap<mojom::blink::PermissionName, PermissionStatus>
      |                                         ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(18,21): note: candidate found by name lookup is 'blink::PermissionStatus'
   18 | using mojom::blink::PermissionStatus;
      |                     ^
../..\third_party/blink/renderer/bindings/core/v8/active_script_wrappable_creation_key.h(84,16): note: candidate found by name lookup is 'blink::PermissionStatus'
   84 |   friend class PermissionStatus;
      |                ^
In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:13:
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(56,5): error: reference to 'PermissionStatus' is ambiguous
   56 |     PermissionStatus status = status_it != permission_status_map_.end()
      |     ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(18,21): note: candidate found by name lookup is 'blink::PermissionStatus'
   18 | using mojom::blink::PermissionStatus;
      |                     ^
../..\third_party/blink/renderer/bindings/core/v8/active_script_wrappable_creation_key.h(84,16): note: candidate found by name lookup is 'blink::PermissionStatus'
   84 |   friend class PermissionStatus;
      |                ^
In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:13:
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(59,46): error: use of undeclared identifier 'status'; did you mean 'stat'?
   59 |     initialized_map.insert(descriptor->name, status);
      |                                              ^~~~~~
      |                                              stat
../../third_party/depot_tools/win_toolchain/vs_files/d325744cf9\Windows Kits\10\Include\10.0.22621.0\ucrt\sys/stat.h(238,39): note: 'stat' declared here
  238 |         static __inline int __CRTDECL stat(char const* const _FileName, struct stat* const _Stat)
      |                                       ^
In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:13:
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(70,44): error: use of undeclared identifier 'status'
   70 |     RegisterPermissionObserver(descriptor, status);
      |                                            ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(107,5): error: reference to 'PermissionStatus' is ambiguous
  107 |     PermissionStatus current_status) {
      |     ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(18,21): note: candidate found by name lookup is 'blink::PermissionStatus'
   18 | using mojom::blink::PermissionStatus;
      |                     ^
../..\third_party/blink/renderer/bindings/core/v8/active_script_wrappable_creation_key.h(84,16): note: candidate found by name lookup is 'blink::PermissionStatus'
   84 |   friend class PermissionStatus;
      |                ^
In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:13:
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(118,55): error: reference to 'PermissionStatus' is ambiguous
  118 | void CachedPermissionStatus::OnPermissionStatusChange(PermissionStatus status) {
      |                                                       ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(18,21): note: candidate found by name lookup is 'blink::PermissionStatus'
   18 | using mojom::blink::PermissionStatus;
      |                     ^
../..\third_party/blink/renderer/bindings/core/v8/active_script_wrappable_creation_key.h(84,16): note: candidate found by name lookup is 'blink::PermissionStatus'
   84 |   friend class PermissionStatus;
      |                ^
In file included from ../../brave/chromium_src/third_party/blink/renderer/core/frame/cached_permission_status.cc:6:
In file included from ../..\third_party/blink/renderer/core/frame/cached_permission_status.h:10:
In file included from gen\third_party/blink/public/mojom/permissions/permission.mojom-blink.h:31:
In file included from gen\url/mojom/origin.mojom-blink.h:30:
In file included from gen\mojo/public/mojom/base/unguessable_token.mojom-blink.h:31:
In file included from ../..\mojo/public/cpp/bindings/lib/wtf_clone_equals_util.h:12:
../..\third_party/blink/renderer/platform/wtf/hash_map.h(358,22): error: assigning to 'blink::mojom::PermissionStatus' from incompatible type 'int (const char *, stat *)'
  358 |     location.value = std::forward<V>(mapped);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
../..\third_party/blink/renderer/platform/wtf/hash_table.h(1294,19): note: in instantiation of function template specialization 'WTF::HashMapTranslator<WTF::HashTraits<blink::mojom::PermissionName>, WTF::HashMapValueTraits<WTF::HashTraits<blink::mojom::PermissionName>, WTF::HashTraits<blink::mojom::PermissionStatus>>>::Store<WTF::KeyValuePair<blink::mojom::PermissionName, blink::mojom::PermissionStatus>, blink::mojom::PermissionName &, int (&)(const char *, stat *)>' requested here
 1294 |   HashTranslator::Store(*entry, std::forward<T>(key),
      |                   ^
../..\third_party/blink/renderer/platform/wtf/hash_map.h(482,25): note: in instantiation of function template specialization 'WTF::HashTable<blink::mojom::PermissionName, WTF::KeyValuePair<blink::mojom::PermissionName, blink::mojom::PermissionStatus>, WTF::KeyValuePairExtractor, WTF::HashMapValueTraits<WTF::HashTraits<blink::mojom::PermissionName>, WTF::HashTraits<blink::mojom::PermissionStatus>>, WTF::HashTraits<blink::mojom::PermissionName>, WTF::PartitionAllocator>::insert<WTF::HashMapTranslator<WTF::HashTraits<blink::mojom::PermissionName>, WTF::HashMapValueTraits<WTF::HashTraits<blink::mojom::PermissionName>, WTF::HashTraits<blink::mojom::PermissionStatus>>>, blink::mojom::PermissionName &, int (&)(const char *, stat *)>' requested here
  482 |   return impl_.template insert<HashMapTranslator<KeyTraits, ValueTraits>>(
      |                         ^
../..\third_party/blink/renderer/platform/wtf/hash_map.h(510,10): note: in instantiation of function template specialization 'WTF::HashMap<blink::mojom::PermissionName, blink::mojom::PermissionStatus>::InlineAdd<blink::mojom::PermissionName &, int (&)(const char *, stat *)>' requested here
  510 |   return InlineAdd(std::forward<IncomingKeyType>(key),
      |          ^
../../..\src/third_party/blink/renderer/core/frame/cached_permission_status.cc(59,21): note: in instantiation of function template specialization 'WTF::HashMap<blink::mojom::PermissionName, blink::mojom::PermissionStatus>::insert<blink::mojom::PermissionName &, int (&)(const char *, stat *)>' requested here
   59 |     initialized_map.insert(descriptor->name, status);
      |                     ^
8 errors generated.

We previously had to make a very similar fix for this PermissionStatus collision
at https://github.com/brave/brave-core/commit/5f1806d3cde22f1147170ca9ea7804b13c3ba995,
but then upstream made a change and it went away. However, the same error is
back now, so reinstating this fix.

Chromium change:
https://source.chromium.org/chromium/chromium/src/+/1924a27af38a16c920fa5e09e1ca9b26e75e7195

commit 1924a27af38a16c920fa5e09e1ca9b26e75e7195
Author: Thomas Nguyen <tungnh@google.com>
Date:   Wed Oct 23 21:54:25 2024 +0000

    [PEPC] Snapshot permission statuses at commit navigation

    When <permission> element is added to the DOM, we'll use IPC to check
    the permission status and it'll update when the IPC callback is
    triggered. This might cause a flicker if the status changes from ASK
    to GRANTED.

    We propose to snapshot permission statuses and cache the statuses at
    the execution context, outlined in: https://docs.google.com/document/d/1pfuiJ7BIdX0dxMzboYIOvPV1mFKQ3HE_11VQNeBJSCc/edit?resourcekey=0->

    Bug: 368238224