[cr145][WIP] Exclude ffmpeg from unsafe buffer check.
Upstream already excludes most of //third_party, but because of how
ffmpeg generates includes the search path ends up going via
../../brave/chromium_src/../../third_party/ffmpeg.

Error:

In file included from ../../third_party/ffmpeg/libavformat/autorename_libavformat_aacdec.c:2:
In file included from ../../brave/chromium_src/../../third_party/ffmpeg/libavformat/aacdec.c:26:
../../brave/chromium_src/../../third_party/ffmpeg/libavformat/avio_internal.h(126,31): error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
  126 |     avio_wl32(pb, MKTAG(s[0], s[1], s[2], s[3]));
      |                               ^
../../brave/chromium_src/../../third_party/ffmpeg/libavformat/avio_internal.h(126,31): note: See //docs/unsafe_buffers.md for help.