Fixes a missing dep in //brave/browser/ui.
While running CI for the Chromium bump:

05:40:55  ../../brave/browser/ui/webui/new_tab_page/brave_new_tab_message_handler.cc:22:10: fatal error: 'brave/components/brave_perf_predictor/browser/buildflags.h' file not found
05:40:55  #include "brave/components/brave_perf_predictor/browser/buildflags.h"
05:40:55           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
05:40:55  1 error generated.

This change adds the missing dependency on
//brave/components/brave_perf_predictor/browser:buildflags