Fix brave_ads missing dep
CI failed with:

12:07:54  In file included from ../../brave/components/brave_ads/browser/notification_helper_mac.mm:15:
12:07:54  ../../chrome/common/chrome_features.h:16:10: fatal error: 'chrome/common/buildflags.h' file not found
12:07:54  #include "chrome/common/buildflags.h"
12:07:54           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:07:54  1 error generated.
12:07:54  [36498/41966] CXX obj/brave/components/brave_ads/browser/browser/ads_tab_helper.o
12:07:54  [36499/41966] CXX obj/brave/components/brave_rewards/browser/browser/rewards_service.o
12:07:54  [36500/41966] CXX obj/brave/components/brave_rewards/browser/browser/external_wallet.o
12:07:54  [36501/41966] CXX obj/brave/components/brave_rewards/browser/browser/rewards_protocol_handler.o
12:07:54  [36502/41966] CXX obj/brave/components/brave_rewards/browser/browser/balance.o
12:07:54  ninja: build stopped: subcommand failed.