Fix BraveAutocompleteController undefined reference error on debug build
This error occurs when builds vr_common target.
In C69, vr_common target is changed from static lib to shared lib.
and vr_common depends on components/omnibox/browser target.
To fix undefined reference to BraveAutocompleteController when builds
vr_common shared lib, components/omnibox/browser should include
brave/components/omnibox/browser.