[cr136] WIP Fixed build error on Android
Error
```
../../chrome/browser/ui/webui/current_channel_logo.cc:32:14: error: use of undeclared identifier 'IDR_PRODUCT_LOGO_32_DEVELOPMENT'
   32 |       return IDR_PRODUCT_LOGO_32_DEVELOPMENT;
      |              ^
1 error generated.
```

Commit marked as WIP because:
1. I didn't yet checked if this code is actually used on Android, and if it is
  - then we can substitute Brave icon on debug build to the gray one like on
  Desktop. Currently on Android on debug build the icon at about:version is the
  orange one;
2. Now, when the function is extracted into a separate source file, the patch
  can be replaced with chromium_src override

Related Chromium commit:
https://source.chromium.org/chromium/chromium/src/+/c134a4989fe915c47d32b83336db1e03750e4943

	extensions: Show chrome logo on chrome://extensions on desktop android

	I ignored the following warning, because I just extracted the existing
	piece of code as a helper function.

	** Presubmit Warnings: 1 **
	Banned functions were used.
	    chrome/browser/ui/webui/current_channel_logo.cc:15:
	      Code gated by GOOGLE_CHROME_BRANDING is effectively untested. This is typically wrong. Valid use cases are glue for private modules shipped alongside Chrome, and installation-related logic.

	Bug: 406136774
	Fixed: 406136774
	Test: Manually confirm the logo is shown on chrome://extensions both on
	light mode and dark mode on desktop android

	Change-Id: I1a0b8b0af46c25f605a2e5047a0bc54212fffa3f
	Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6399693