[Linux] Removed unnecessary chromium_src overrides.
The fix in the overrides is no longer needed due to the fix upstream.

Chromium change:

https://chromium.googlesource.com/chromium/src/+/b544f41b2121687e8b52136a8ca343d0a968e42d

commit b544f41b2121687e8b52136a8ca343d0a968e42d
Author: Chen-Yu Tsai <wens@cloudmosa.com>
Date:   Wed Nov 6 20:51:46 2019 +0000

    media: Declare GpuMojoMediaClient::gpu_memory_buffer_factory_ for ChromeOS only

    GpuMojoMediaClient::gpu_memory_buffer_factory_ is guarded by
    BUILDFLAG(USE_CHROMEOS_MEDIA_ACCELERATION), however it is only used in
    the ChromeOS specific code path.

    This results in the following error if standard Chrome is built with
    use_vaapi=true or use_v4l2_codec=true on Linux:

    In file included from ../../media/mojo/services/gpu_mojo_media_client.cc:5:
    ../../media/mojo/services/gpu_mojo_media_client.h:77:38: error:
        private field 'gpu_memory_buffer_factory_' is not used
        [-Werror,-Wunused-private-field]
      gpu::GpuMemoryBufferFactory* const gpu_memory_buffer_factory_;

    Add "defined(OS_CHROMEOS)" to the #ifs that guard the field declaration
    and assignment in the constructor to match the code path that uses it.