Fixes inconsistent Google search favicon in omnibox. (uplift to 1.75.x) (#27656)
* Uplift of #27650 (squashed) to release

* Fixes build error due to missing dep. (#27668)

../../brave/chromium_src/components/omnibox/browser/omnibox_edit_model.cc:11:10: fatal error: 'components/vector_icons/vector_icons.h' file not found
    11 | #include "components/vector_icons/vector_icons.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

---------

Co-authored-by: Max Karolinskiy <41635752+mkarolin@users.noreply.github.com>