[cr150] Only preserve `kPrefProvider` rules in `ContentSettingsDefaultsKeeper`
The keeper snapshotted every wildcard shields rule whose source wasn't
`kDefaultProvider`, then re-applied them through the user pref store --
including policy-provided defaults (e.g. AdBlockOnlyMode's `BRAVE_REFERRERS =
ALLOW`), which would survive as user-level rules after the policy was removed.
Restrict the filter to `kPrefProvider` so only user-owned rules are preserved;
other providers re-publish their own state.

This fixes `AdblockOnlyModeBrowserTest.AdblockOnlyModeDisablingRestoresSettings`
which was failing like this:

[ RUN      ] AdblockOnlyModeBrowserTest.AdblockOnlyModeDisablingRestoresSettings
[19680:27004:0527/115138.143:ERROR:components\gcm_driver\gcm_driver_desktop.cc:1056] Unable to get the InstanceID data: cannot start the GCM Client
[19680:27004:0527/115138.144:ERROR:components\gcm_driver\gcm_driver_desktop.cc:1056] Unable to get the InstanceID data: cannot start the GCM Client
[19680:27004:0527/115138.155:ERROR:components\gcm_driver\gcm_driver_desktop.cc:992] Unable to add the InstanceID data: cannot start the GCM Client
[19680:27004:0527/115138.155:ERROR:components\gcm_driver\gcm_driver_desktop.cc:848] Unable to get the InstanceID token: cannot start the GCM Client
[19680:27004:0527/115138.155:ERROR:components\gcm_driver\gcm_driver_desktop.cc:992] Unable to add the InstanceID data: cannot start the GCM Client
[19680:27004:0527/115138.155:ERROR:components\gcm_driver\gcm_driver_desktop.cc:848] Unable to get the InstanceID token: cannot start the GCM Client
..\..\brave\browser\brave_shields\ad_block_only_mode_browsertest.cc(126): error: Value of: brave_shields::AreReferrersAllowed(host_content_settings_map(), GURL())
  Actual: true
Expected: false
Stack trace:
	brave_browser_tests!brave_shields::AdblockOnlyModeBrowserTestBase::VerifySettingsCausingWebCompatIssues [0x7ff778c18ef0+780] (D:\ws\src\brave\browser\brave_shields\ad_block_only_mode_browsertest.cc:125)
	brave_browser_tests!brave_shields::AdblockOnlyModeBrowserTest_AdblockOnlyModeDisablingRestoresSettings_Test::RunTestOnMainThread [0x7ff778c18721+171] (D:\ws\src\brave\browser\brave_shields\ad_block_only_mode_browsertest.cc:287)
	brave_browser_tests!content::BrowserTestBase::ProxyRunTestOnMainThreadLoop [0x7ff78d7a3b7e+53e] (D:\ws\src\content\public\test\browser_test_base.cc:1019)
	brave_browser_tests!base::OnceCallback<void ()>::Run [0x7ff778bca5ad+8d] (D:\ws\src\base\functional\callback.h:155)
	brave_browser_tests!content::BrowserMainRunnerImpl::Run [0x7ff77e115520+a0] (D:\ws\src\content\browser\browser_main_runner_impl.cc:149)
	brave_browser_tests!content::BrowserMain [0x7ff77e10e4d6+a6] (D:\ws\src\content\browser\browser_main.cc:32)
	brave_browser_tests!content::RunBrowserProcessMain [0x7ff7811c9a57+137] (D:\ws\src\content\app\content_main_runner_impl.cc:697)
	brave_browser_tests!content::ContentMainRunnerImpl::RunBrowser [0x7ff7811cc5f8+668] (D:\ws\src\content\app\content_main_runner_impl.cc:1331)
	brave_browser_tests!content::ContentMainRunnerImpl::Run [0x7ff7811cbf2e+7be] (D:\ws\src\content\app\content_main_runner_impl.cc:1162)
	brave_browser_tests!content::RunContentProcess [0x7ff7811c8fe3+563] (D:\ws\src\content\app\content_main.cc:356)
	brave_browser_tests!content::ContentMain [0x7ff7811c91db+7b] (D:\ws\src\content\app\content_main.cc:369)
	brave_browser_tests!content::BrowserTestBase::SetUp [0x7ff78d7a2a77+12a7] (D:\ws\src\content\public\test\browser_test_base.cc:615)
	brave_browser_tests!InProcessBrowserTest::SetUp [0x7ff782f9cf06+1d6] (D:\ws\src\chrome\test\base\in_process_browser_test.cc:559)
[  FAILED  ] AdblockOnlyModeBrowserTest.AdblockOnlyModeDisablingRestoresSettings, where TypeParam =  and GetParam() =  (2980 ms)