Fixed build failure from side_panel.h (#37245)
Resolves - no issue. simple build fix

/brave/browser/ui/sidebar/buildflags should be in public_deps.

======== BUILD FAILURE LOG ========================================================
05:31:05  In file included from ../../chrome/browser/lens/region_search/lens_region_search_controller.cc:17:
05:31:05  In file included from ../../brave/chromium_src/chrome/browser/ui/views/frame/browser_view.h:14:
05:31:05  ../../brave/chromium_src/chrome/browser/ui/views/side_panel/side_panel.h:11:10: fatal error: 'brave/browser/ui/sidebar/buildflags/buildflags.h' file not found
05:31:05     11 | #include "brave/browser/ui/sidebar/buildflags/buildflags.h"
05:31:05        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
05:31:05  1 error generated.
================================================================================

Also removed unnecessary side_panel.h including from browser_view.h.
and added missing side_panel.h includings. It was hidden due to unnecessary including from browser_view.h