[cr152] Fixed size_t conversion build error on arm32 and Windows
Error messages were:

../../brave/third_party/blink/renderer/core/farbling/brave_session_cache.cc:291:59: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  289 |           ? blink::WebGLFarbledExtensionHandler::CreateBalancedHandler(
      |             ~~~~~
  290 |                 supported_extensions,
  291 |                 default_shields_settings_->farbling_token.low())
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../../brave/third_party/blink/renderer/core/farbling/brave_session_cache.cc:361:12: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_type' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  361 |       data[pixel_index] = data[pixel_index] ^ (bit & 0x1);
      |       ~~~~ ^~~~~~~~~~~
../../brave/third_party/blink/renderer/core/farbling/brave_session_cache.cc:361:32: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_type' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  361 |       data[pixel_index] = data[pixel_index] ^ (bit & 0x1);
      |                           ~~~~ ^~~~~~~~~~~

and

  ../../brave/third_party/blink/renderer/core/farbling/brave_session_cache.cc(296,57): error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    295 |           blink::WebGLFarbledExtensionHandler::CreateHandler(
        |           ~~~~~
    296 |               default_shields_settings_->farbling_token.low());
        |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
  1 error generated.

Chromium changes:
https://source.chromium.org/chromium/chromium/src/+/d8058598c0efdede729abbab5fde213ec7b06bc7

commit d8058598c0efdede729abbab5fde213ec7b06bc7
Author: Kent Tamura <tkent@chromium.org>
Date:   Thu Jul 9 17:51:43 2026 -0700

    Add -Wshorten-64-to-32 and -Wtautological-unsigned-zero-compare to `inside_blink` config

    Bug: 514751964
    Change-Id: I4bf0cd742df4b4ef833dee0402a08b9efa7e83d1
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/8062845
    Reviewed-by: Ryan Hamilton <rch@chromium.org>
    Commit-Queue: Kent Tamura <tkent@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1659987}