[CodeHealth] Add v8/buildflags to brave_chrome_browser_public_deps
Add //brave/components/v8/buildflags to brave_chrome_browser_public_deps
so it ends up in browser_public_dependencies. This fixes the missing
dependency issue that caused build failures when brave_browser_features.h
(which includes brave/components/v8/buildflags/buildflags.h) was included
by UI files like brave_browser_view.cc and brave_omnibox_view_views.cc.

This fixes compilation errors like:
  fatal error: 'brave/components/v8/buildflags/buildflags.h' file not found