Add //chrome/app/theme:theme_resources deps in brave_theme_resources
Resolving missing generated header in Release build
```
../../brave/chromium_src/chrome/grit/theme_resources.h:2:10: fatal
error: 'gen/chrome/grit/theme_resources.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Auditors: @bbondy, @simonhong