Fixes build error due to missing dep.
 ../../brave/chromium_src/components/omnibox/browser/omnibox_edit_model.cc:11:10: fatal error: 'components/vector_icons/vector_icons.h' file not found
    11 | #include "components/vector_icons/vector_icons.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~