[cr140] Added missing `//v8:cppgc_headers` dep
Dep added to address this build failure:

 In file included from ../../brave/components/script_injector/renderer/script_injector_unittest.cc:7:
 In file included from ../..\brave/components/script_injector/renderer/script_injector_render_frame_observer.h:16:
 In file included from ../..\content/public/renderer/render_frame_observer.h:32:
 In file included from ../..\third_party/blink/public/web/web_performance_metrics_for_reporting.h:15:
 In file included from ../..\third_party/blink/public/platform/web_private_ptr.h:36:
 In file included from ../..\third_party/blink/renderer/platform/heap/cross_thread_persistent.h:8:
 In file included from ../..\third_party/blink/renderer/platform/heap/persistent.h:14:
 ../..\v8/include/cppgc/cross-thread-persistent.h(10,10): fatal error: 'cppgc/internal/persistent-node.h' file not found
    10 | #include "cppgc/internal/persistent-node.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.