Fix relative paths
This fixes the following error during `npm run sync`:

/home/francois/devel/brave-browser
> gclient runhooks
80>use_relative_hooks is deprecated, please remove it from DEPS. (it was merged in use_relative_paths)
23>use_relative_hooks is deprecated, please remove it from DEPS. (it was merged in use_relative_paths)
Running hooks:  96% (94/97) bootstrap
________ running 'vpython src/brave/script/bootstrap.py' in '/home/francois/devel/brave-browser/src/brave'
/home/francois/devel/brave-browser/vendor/depot_tools/.cipd_bin/.cipd/pkgs/0/fI6WggdkRyN1r91MnTeApc2_gyTtXfYpueHZVLcaF8gC/vpython: could not resolve options: failed to resolve Python script: stat /home/francois/devel/brave-browser/src/brave/src/brave/script/bootstrap.py: no such file or directory
Error: Command 'vpython src/brave/script/bootstrap.py' returned non-zero exit status 1 in /home/francois/devel/brave-browser/src/brave