[cr132][Android] Missing public_deps at upstream
There is compile error
```
 In file included from ../../brave/chromium_src/chrome/browser/prefs/browser_prefs.cc:67:
 In file included from ../../../src/chrome/browser/prefs/browser_prefs.cc:25:
 ../../chrome/browser/chrome_content_browser_client.h:31:10: fatal error: 'components/guest_view/buildflags/buildflags.h' file not found
    31 | #include "components/guest_view/buildflags/buildflags.h"
       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1 error generated.
```
Happens because there is no public path between `//chrome/browser/prefs:impl` and `//components/guest_view/buildflags:buildflags` targets.

`//components/guest_view/buildflags:buildflags` is deps for `//chrome/browser`,
and `//chrome/browser/prefs:impl` is is also deps for `//chrome/browser`.

Chromium change:
https://source.chromium.org/chromium/chromium/src/+/f618031bf39bd77f482fe9331708738fe212ce17

	Reland "Move enable_guest_view out of extensions"

	This is a reland of commit d643d0bb1c8553dd9f69de9d6c129d4e49ce1770

	Patch set 1 is as landed, patch set 2 fixes chromecast build by
	adding enable_guest_view to the linux.gni config file.

	Original change's description:
	> Move enable_guest_view out of extensions
	>
	> We should be able to depend on components/guest_view and determine
	> if it is indeed enabled.
	> Bug: 40202416, 356671305
	>
	> Change-Id: I6d77ef2dcb1194f1331411cdcd4d1269144528eb
	> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5994331
	> Reviewed-by: Joe Mason <joenotcharles@google.com>
	> Reviewed-by: Kevin McNee <mcnee@chromium.org>
	> Reviewed-by: Avi Drissman <avi@chromium.org>
	> Commit-Queue: Dave Tapuska <dtapuska@chromium.org>
	> Reviewed-by: Reilly Grant <reillyg@chromium.org>
	> Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
	> Cr-Commit-Position: refs/heads/main@{#1379199}

	Bug: 40202416, 356671305
	Change-Id: I70a85fafdaede43a335f99b372b84dbc5f6aa57e
	Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6000816